\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{paredebranca}

\LoadClass[12pt,openright]{memoir}

%\RequirePackage{styles/pb-layout}
\RequirePackage{styles/pb-fonts}

\RequirePackage{titlesec}
\RequirePackage{fancyhdr}
\RequirePackage{setspace}
\RequirePackage{xcolor}
\RequirePackage{emptypage}
\RequirePackage[a5paper,top=2.5cm,bottom=2.5cm,inner=3cm,outer=2cm]{geometry}

\RequirePackage{styles/pb-cover}
\RequirePackage{styles/pb-chapter}
